//==================================================
// This file contains the Excluded objects
// Generated By User: svgpdv25ommagdy
// Format Version: 2
// Date: Thu Feb 20 23:07:51 2025
// ExclMode: default
//==================================================
CHECKSUM: "1527670684 2059093668"
INSTANCE: mytop.ALU_inst0
Block 13 "2517856575" "C <= 'b0;"
Block 19 "1872675820" "C <= 'b0;"
CHECKSUM: "1527670684 1539787523"
INSTANCE: mytop.ALU_inst0
Condition 3 "3865562944" "(a_en && b_en) 1 -1" (1 "01")
Condition 3 "3865562944" "(a_en && b_en) 1 -1" (2 "10")
CHECKSUM: "1527670684 3329528976"
INSTANCE: mytop.ALU_inst0
Branch 0 "3809248909" "(~rst_n)" (8) "(~rst_n) 0,1,1,default,-,-,-,-"
Branch 0 "3809248909" "(~rst_n)" (17) "(~rst_n) 0,1,0,-,0,-,1,MISSING_DEFAULT"
Branch 0 "3809248909" "(~rst_n)" (12) "(~rst_n) 0,1,0,-,1,default,-,-"
